# @generated by defs/codegen/generate.py from defs/bloomberg.toml — DO NOT EDIT

from __future__ import annotations

from typing import Literal

CDX_INFO_FIELDS: tuple[str, ...] = (
    "ROLLING_SERIES",
    "VERSION",
    "ON_THE_RUN_CURRENT_BD_INDICATOR",
    "CDS_FIRST_ACCRUAL_START_DATE",
    "NAME",
    "NUM_CURRENT_COMPANIES_CCY_TKR",
    "NUM_ORIG_COMPANIES_CRNCY_TKR",
    "PX_LAST",
)

CDX_PRICING_FIELDS: tuple[str, ...] = (
    "PX_LAST",
    "PX_BID",
    "PX_ASK",
    "UPFRONT_LAST",
    "UPFRONT_BID",
    "UPFRONT_ASK",
    "CDS_FLAT_SPREAD",
    "UPFRONT_FEE",
    "PV_CDS_PREMIUM_LEG",
    "PV_CDS_DEFAULT_LEG",
)

CDX_RISK_FIELDS: tuple[str, ...] = (
    "SW_CNV_BPV",
    "SW_EQV_BPV",
    "CDS_SPREAD_MID_MODIFIED_DURATION",
    "CDS_SPREAD_MID_CONVEXITY",
    "RECOVERY_RATE_SEN",
    "CDS_RECOVERY_RT",
)

BLOOMBERG_TOOL_NAMES: tuple[str, ...] = (
    "xbbg_bdp",
    "xbbg_bdh",
    "xbbg_bds",
    "xbbg_bdib",
    "xbbg_bdtick",
    "xbbg_check_entitlements",
    "xbbg_bql",
    "xbbg_bsrch",
    "xbbg_bqr",
    "xbbg_bflds",
    "xbbg_beqs",
    "xbbg_yas",
    "xbbg_preferreds",
    "xbbg_corporate_bonds",
    "xbbg_index_members",
    "xbbg_resolve_isins",
    "xbbg_issuer_isins",
    "xbbg_resolve_venues",
    "xbbg_auction_snapshot",
    "xbbg_etf_holdings",
    "xbbg_stream_snapshot",
    "xbbg_mktbar_snapshot",
    "xbbg_depth_snapshot",
    "xbbg_ext_ticker",
    "xbbg_ext_futures",
    "xbbg_ext_cdx",
    "xbbg_ext_currency",
    "xbbg_ext_bql_builder",
    "xbbg_ext_chart_spec",
    "xbbg_ext_market_session",
    "xbbg_ext_yas_overrides",
    "xbbg_ext_constants",
    "xbbg_ext_columns",
    "xbbg_ext_calculate",
)

REFERENCE_FORMATS: tuple[str, ...] = ("long", "long_typed", "long_metadata")

HISTORICAL_FORMATS: tuple[str, ...] = ("long", "long_typed", "long_metadata", "semi_long")

OVERFLOW_POLICIES: tuple[str, ...] = ("drop_newest", "block")

DEFAULT_MAX_SECURITIES = 25

DEFAULT_MAX_FIELDS = 25

DEFAULT_MAX_ROWS = 500

DEFAULT_MAX_STRING_CHARS = 2_000

DEFAULT_MAX_RESULT_BYTES = 1_048_576

DEFAULT_MAX_RESULT_NODES = 50_000

DEFAULT_MAX_CONTENT_BYTES = 65_536

DEFAULT_MAX_CONTENT_ROWS = 50

DEFAULT_MAX_BQL_QUERY_CHARS = 4_000

DEFAULT_MAX_SEARCH_SPEC_CHARS = 1_000

DEFAULT_MAX_STREAM_UPDATES = 10

DEFAULT_MAX_STREAM_WAIT_MS = 15_000

MAX_RESULT_DEPTH = 32

MIN_TOOL_RESULT_NODES = 10

MIN_TOOL_RESULT_BYTES = 256

MAX_ENTITLEMENT_EIDS = 10_000

MAX_BLOOMBERG_EID = 2_147_483_647

ERROR_KEYS: tuple[str, ...] = (
    "error",
    "errors",
    "responseError",
    "responseErrors",
    "securityError",
    "securityErrors",
    "fieldException",
    "fieldExceptions",
    "fieldErrors",
    "unsubscribeError",
    "response_error",
    "response_errors",
    "security_error",
    "security_errors",
    "field_exception",
    "field_exceptions",
    "field_errors",
    "unsubscribe_error",
)

PRIORITY_KEYS: tuple[str, ...] = (
    "error",
    "errors",
    "responseError",
    "responseErrors",
    "securityError",
    "securityErrors",
    "fieldException",
    "fieldExceptions",
    "fieldErrors",
    "unsubscribeError",
    "response_error",
    "response_errors",
    "security_error",
    "security_errors",
    "field_exception",
    "field_exceptions",
    "field_errors",
    "unsubscribe_error",
    "hasErrors",
    "truncated",
    "truncatedInput",
    "eidData",
    "eidDataTruncation",
    "entitled",
    "failedEids",
    "diagnostics",
    "metadata",
    "rowCount",
    "updateCount",
    "renderable",
    "spec",
)

TRUNCATION_REASON_ORDER: tuple[str, ...] = (
    "max_rows",
    "max_string_chars",
    "max_result_bytes",
    "max_result_nodes",
    "max_result_depth",
    "circular_reference",
    "binary_data",
    "unsupported_value",
    "upstream_truncation",
)

CHART_SOURCES: tuple[str, ...] = ("bdh", "bdib", "holdings", "depth", "rows")

CHART_KINDS: tuple[str, ...] = ("line", "area", "bar", "scatter", "candlestick", "depth")

X_FIELD_CANDIDATES: tuple[str, ...] = ("date", "time", "datetime", "timestamp")

LABEL_FIELD_CANDIDATES: tuple[str, ...] = ("ticker", "security", "member", "name", "label")

SERIES_FIELD_CANDIDATES: tuple[str, ...] = ("ticker", "security", "field", "side", "category")

VALUE_FIELD_CANDIDATES: tuple[str, ...] = (
    "value",
    "PX_LAST",
    "close",
    "price",
    "weight",
    "marketValue",
    "market_value",
)

OPEN_FIELD_CANDIDATES: tuple[str, ...] = ("open", "OPEN", "PX_OPEN")

HIGH_FIELD_CANDIDATES: tuple[str, ...] = ("high", "HIGH", "PX_HIGH")

LOW_FIELD_CANDIDATES: tuple[str, ...] = ("low", "LOW", "PX_LOW")

CLOSE_FIELD_CANDIDATES: tuple[str, ...] = ("close", "CLOSE", "PX_LAST", "last", "value")

SIDE_FIELD_CANDIDATES: tuple[str, ...] = ("side", "SIDE", "type")

PRICE_FIELD_CANDIDATES: tuple[str, ...] = ("price", "PRICE", "px", "PX")

SIZE_FIELD_CANDIDATES: tuple[str, ...] = ("size", "SIZE", "quantity", "qty", "volume")

CHART_DEFAULTS = {
    "bdh": "line",
    "bdib": "candlestick",
    "holdings": "bar",
    "depth": "depth",
    "rows": "line",
}

ARROW_METADATA_KEYS = {
    "xbbg.security_errors": "securityErrors",
    "xbbg.field_exceptions": "fieldExceptions",
    "xbbg.eid_data": "eidData",
}

ReferenceFormat = Literal["long", "long_typed", "long_metadata"]
HistoricalFormat = Literal["long", "long_typed", "long_metadata", "semi_long"]
OverflowPolicy = Literal["drop_newest", "block"]
ChartSource = Literal["bdh", "bdib", "holdings", "depth", "rows"]
ChartKind = Literal["line", "area", "bar", "scatter", "candlestick", "depth"]
