# @generated by defs/codegen/generate.py from defs/bloomberg.toml — DO NOT EDIT

from __future__ import annotations

from enum import Enum


class Service(str, Enum):
    """Bloomberg service URIs."""

    APIFLDS = "//blp/apiflds"
    """Field metadata service for field info and search (bflds)."""

    BQLSVC = "//blp/bqlsvc"
    """Bloomberg Query Language service (bql)."""

    EXRSVC = "//blp/exrsvc"
    """Excel/Search service for Bloomberg searches (bsrch)."""

    INSTRUMENTS = "//blp/instruments"
    """Instruments service for security lookup (blkp)."""

    MKTBAR = "//blp/mktbar"
    """Real-time streaming OHLC bars (mktbar)."""

    MKTDATA = "//blp/mktdata"
    """Real-time market data subscriptions (subscribe, stream)."""

    MKTDEPTH = "//blp/mktdepthdata"
    """Level 2 market depth / order book data (depth). Requires a B-PIPE environment and applicable entitlements."""

    MKTLIST = "//blp/mktlist"
    """Option chains and futures chains (chains). Requires a B-PIPE environment and applicable entitlements."""

    MKTVWAP = "//blp/mktvwap"
    """Real-time VWAP subscription service (vwap)."""

    REFDATA = "//blp/refdata"
    """Reference data service for bdp, bdh, bds, bdib, bdtick, beqs, bport."""

    TASVC = "//blp/tasvc"
    """Technical Analysis service for study calculations (bta)."""


class Operation(str, Enum):
    """Bloomberg request operation names."""

    BEQS = "BeqsRequest"
    """Bloomberg Equity Screening (BEQS)."""

    BQL_SEND_QUERY = "sendQuery"
    """Bloomberg Query Language query (bql)."""

    CURVE_LIST = "curveListRequest"
    """List yield curves (bcurves)."""

    EXCEL_GET_GRID = "ExcelGetGridRequest"
    """Bloomberg Search/Excel grid request (bsrch)."""

    FIELD_INFO = "FieldInfoRequest"
    """Get field metadata (type, description)."""

    FIELD_SEARCH = "FieldSearchRequest"
    """Search for fields by keyword."""

    GOVT_LIST = "govtListRequest"
    """List government securities (bgovts)."""

    HISTORICAL_DATA = "HistoricalDataRequest"
    """Historical time series data (bdh)."""

    INSTRUMENT_LIST = "instrumentListRequest"
    """Security lookup by name (blkp)."""

    INTRADAY_BAR = "IntradayBarRequest"
    """Intraday OHLCV bars (bdib)."""

    INTRADAY_TICK = "IntradayTickRequest"
    """Intraday tick data (bdtick)."""

    PORTFOLIO_DATA = "PortfolioDataRequest"
    """Portfolio data request (bport)."""

    RAW_REQUEST = ""
    """Raw session.sendRequest() call (no operation name needed)."""

    REFERENCE_DATA = "ReferenceDataRequest"
    """Single point-in-time data (bdp, bds)."""

    STUDY_REQUEST = "studyRequest"
    """Technical analysis study request (bta)."""


class ExtractorHint(str, Enum):
    """Hint for which Arrow extractor to use."""

    BQL = "bql"
    """BQL: Bloomberg Query Language responses."""

    BSRCH = "bsrch"
    """BSRCH: Bloomberg Search responses."""

    BULK = "bulk"
    """Bulk data extractor: [ticker, field, row_idx, col1, col2, ...]"""

    FIELD_INFO = "fieldinfo"
    """Field info extractor: [field, type, description, category]"""

    GENERIC = "generic"
    """Generic flattener: [path, type, value_str, value_num, value_date]"""

    HISTDATA = "histdata"
    """Historical data extractor: [ticker, date, field, value, ...]"""

    INTRADAY_BAR = "intraday_bar"
    """Intraday bar extractor: [ticker, time, open, high, low, close, volume, ...]"""

    INTRADAY_TICK = "intraday_tick"
    """Intraday tick extractor: [ticker, time, type, value, size, ...]"""

    REFDATA = "refdata"
    """Reference data extractor: [ticker, field, value, ...]"""


class Format(str, Enum):
    """Output format for reference data."""

    LONG = "long"
    """Long format with all values as strings (default, backwards-compatible)."""

    LONG_TYPED = "long_typed"
    """Long format with typed value columns."""

    LONG_WITH_METADATA = "long_metadata"
    """Long format with string values and dtype metadata column."""

    SEMI_LONG = "semi_long"
    """Semi-long format with one row per ticker/timestamp and fields as columns."""


class OutputMode(str, Enum):
    """Output mode for generic requests."""

    ARROW = "arrow"
    """Convert to Arrow RecordBatch using appropriate extractor."""

    JSON = "json"
    """Return raw JSON as a single-column Arrow table."""


class VolSurfacePreset(str, Enum):
    """Built-in Bloomberg implied-volatility field presets."""

    DELTA_1M_2M = "DELTA_1M_2M"
    MONEYNESS_30D = "MONEYNESS_30D"
    MONEYNESS_60D = "MONEYNESS_60D"
    MONEYNESS_3M = "MONEYNESS_3M"
    MONEYNESS_6M = "MONEYNESS_6M"
    MONEYNESS_12M = "MONEYNESS_12M"


FORMATS: tuple[str, ...] = ("long", "long_typed", "long_metadata", "semi_long")
"""Output format for reference and historical data."""

FORMAT_ALIASES: tuple[str, ...] = ("typed", "metadata", "with_metadata", "wide")
"""Extra spellings FORMATS also accepts but which are not advertised."""

FORMAT_DEFAULT = "long"
"""Value used when the caller omits it."""

FORMAT_VALUES = "long, long_typed, long_metadata, semi_long"
"""Canonical FORMATS as a list for error messages and docstrings."""

OVERFLOW_POLICIES: tuple[str, ...] = ("block", "drop_newest")
"""Subscription behaviour when a consumer cannot keep up with Bloomberg."""

OVERFLOW_POLICY_ALIASES: tuple[str, ...] = ("dropnewest",)
"""Extra spellings OVERFLOW_POLICIES also accepts but which are not advertised."""

OVERFLOW_POLICY_DEFAULT = "drop_newest"
"""Value used when the caller omits it."""

OVERFLOW_POLICY_VALUES = "block, drop_newest"
"""Canonical OVERFLOW_POLICIES as a list for error messages and docstrings."""

VALIDATION_MODES: tuple[str, ...] = ("disabled", "lenient", "strict")
"""Field validation applied before a request is sent."""

VALIDATION_MODE_ALIASES: tuple[str, ...] = ("off", "none")
"""Extra spellings VALIDATION_MODES also accepts but which are not advertised."""

VALIDATION_MODE_DEFAULT = "disabled"
"""Value used when the caller omits it."""

VALIDATION_MODE_VALUES = "disabled, lenient, strict"
"""Canonical VALIDATION_MODES as a list for error messages and docstrings."""

SDK_LOG_LEVELS: tuple[str, ...] = ("debug", "error", "fatal", "info", "off", "trace", "warn")
"""Verbosity of the Bloomberg C SDK's own logging."""

SDK_LOG_LEVEL_ALIASES: tuple[str, ...] = ("warning",)
"""Extra spellings SDK_LOG_LEVELS also accepts but which are not advertised."""

SDK_LOG_LEVEL_DEFAULT = "off"
"""Value used when the caller omits it."""

SDK_LOG_LEVEL_VALUES = "debug, error, fatal, info, off, trace, warn"
"""Canonical SDK_LOG_LEVELS as a list for error messages and docstrings."""

CDX_INFO_FIELDS: tuple[str, ...] = (
    "ROLLING_SERIES",
    "VERSION",
    "ON_THE_RUN_CURRENT_BD_INDICATOR",
    "CDS_FIRST_ACCRUAL_START_DATE",
    "NAME",
    "NUM_CURRENT_COMPANIES_CCY_TKR",
    "NUM_ORIG_COMPANIES_CRNCY_TKR",
    "PX_LAST",
)

CDX_PRICING_FIELDS: tuple[str, ...] = (
    "PX_LAST",
    "PX_BID",
    "PX_ASK",
    "UPFRONT_LAST",
    "UPFRONT_BID",
    "UPFRONT_ASK",
    "CDS_FLAT_SPREAD",
    "UPFRONT_FEE",
    "PV_CDS_PREMIUM_LEG",
    "PV_CDS_DEFAULT_LEG",
)

CDX_RISK_FIELDS: tuple[str, ...] = (
    "SW_CNV_BPV",
    "SW_EQV_BPV",
    "CDS_SPREAD_MID_MODIFIED_DURATION",
    "CDS_SPREAD_MID_CONVEXITY",
    "RECOVERY_RATE_SEN",
    "CDS_RECOVERY_RT",
)

TA_STUDIES: dict[str, str] = {
    "smavg": "smavgStudyAttributes",
    "sma": "smavgStudyAttributes",
    "emavg": "emavgStudyAttributes",
    "ema": "emavgStudyAttributes",
    "wmavg": "wmavgStudyAttributes",
    "wma": "wmavgStudyAttributes",
    "vmavg": "vmavgStudyAttributes",
    "vma": "vmavgStudyAttributes",
    "tmavg": "tmavgStudyAttributes",
    "tma": "tmavgStudyAttributes",
    "ipmavg": "ipmavgStudyAttributes",
    "rsi": "rsiStudyAttributes",
    "macd": "macdStudyAttributes",
    "mao": "maoStudyAttributes",
    "momentum": "momentumStudyAttributes",
    "mom": "momentumStudyAttributes",
    "roc": "rocStudyAttributes",
    "boll": "bollStudyAttributes",
    "bb": "bollStudyAttributes",
    "kltn": "kltnStudyAttributes",
    "keltner": "kltnStudyAttributes",
    "mae": "maeStudyAttributes",
    "te": "teStudyAttributes",
    "al": "alStudyAttributes",
    "dmi": "dmiStudyAttributes",
    "adx": "dmiStudyAttributes",
    "tas": "tasStudyAttributes",
    "stoch": "tasStudyAttributes",
    "trender": "trenderStudyAttributes",
    "ptps": "ptpsStudyAttributes",
    "parabolic": "ptpsStudyAttributes",
    "sar": "ptpsStudyAttributes",
    "chko": "chkoStudyAttributes",
    "ado": "adoStudyAttributes",
    "vat": "vatStudyAttributes",
    "tvat": "tvatStudyAttributes",
    "atr": "atrStudyAttributes",
    "hurst": "hurstStudyAttributes",
    "fg": "fgStudyAttributes",
    "fear_greed": "fgStudyAttributes",
    "goc": "gocStudyAttributes",
    "ichimoku": "gocStudyAttributes",
    "cmci": "cmciStudyAttributes",
    "wlpr": "wlprStudyAttributes",
    "williams": "wlprStudyAttributes",
    "maxmin": "maxminStudyAttributes",
    "rex": "rexStudyAttributes",
    "etd": "etdStudyAttributes",
    "pd": "pdStudyAttributes",
    "rv": "rvStudyAttributes",
    "pivot": "pivotStudyAttributes",
    "or": "orStudyAttributes",
    "pcr": "pcrStudyAttributes",
    "bs": "bsStudyAttributes",
}

TA_DEFAULTS: dict[str, dict[str, str | int | float]] = {
    "smavgStudyAttributes": {"period": 20, "priceSourceClose": "PX_LAST"},
    "emavgStudyAttributes": {"period": 20, "priceSourceClose": "PX_LAST"},
    "wmavgStudyAttributes": {"period": 20, "priceSourceClose": "PX_LAST"},
    "vmavgStudyAttributes": {"period": 20, "priceSourceClose": "PX_LAST"},
    "tmavgStudyAttributes": {"period": 20, "priceSourceClose": "PX_LAST"},
    "rsiStudyAttributes": {"period": 14, "priceSourceClose": "PX_LAST"},
    "macdStudyAttributes": {"maPeriod1": 12, "maPeriod2": 26, "sigPeriod": 9, "priceSourceClose": "PX_LAST"},
    "bollStudyAttributes": {"period": 20, "upperBand": 2.0, "lowerBand": 2.0, "priceSourceClose": "PX_LAST"},
    "dmiStudyAttributes": {
        "period": 14,
        "priceSourceHigh": "PX_HIGH",
        "priceSourceLow": "PX_LOW",
        "priceSourceClose": "PX_LAST",
    },
    "atrStudyAttributes": {
        "maType": "Simple",
        "period": 14,
        "priceSourceHigh": "PX_HIGH",
        "priceSourceLow": "PX_LOW",
        "priceSourceClose": "PX_LAST",
    },
    "tasStudyAttributes": {
        "periodK": 14,
        "periodD": 3,
        "periodDS": 3,
        "periodDSS": 3,
        "priceSourceHigh": "PX_HIGH",
        "priceSourceLow": "PX_LOW",
        "priceSourceClose": "PX_LAST",
    },
}

INDEX_MEMBER_FIELDS: tuple[str, ...] = ("INDX_MWEIGHT", "INDX_MEMBERS", "INDX_MEMBERS3")
