#!/usr/bin/env python3
"""Generate xbbg's package stub without importing xbbg or its native extension.

Run after the Rust stub_gen binary when regenerating the distributed stubs:
    python scripts/generate_package_stub.py
"""

from __future__ import annotations

import argparse
import ast
from collections import defaultdict
from functools import cache
from pathlib import Path
import runpy

PACKAGE_DIR = Path(__file__).resolve().parents[1] / "py-xbbg" / "src" / "xbbg"


def generate_stub(package_dir: Path) -> str:
    """Render the canonical export registry using the runtime's lazy import routes."""
    registry = runpy.run_path(str(package_dir / "_exports.py"))
    package_ast = ast.parse((package_dir / "__init__.py").read_text(encoding="utf-8"))
    routes_function = next(
        node
        for node in package_ast.body
        if isinstance(node, ast.FunctionDef) and node.name == "_build_lazy_attr_exports"
    )
    # Execute only the registry-to-module mapping, not package/SDK initialization.
    routes_ast = ast.Module(body=[routes_function], type_ignores=[])
    exec(compile(routes_ast, "xbbg/__init__.py", "exec"), registry)
    routes = registry["_build_lazy_attr_exports"]()

    @cache
    def reexports(module: str) -> dict[str, tuple[str, str]]:
        if module == "_core":
            return {}
        source = package_dir.joinpath(*module.split(".")).with_suffix(".py")
        tree = ast.parse(source.read_text(encoding="utf-8"))
        imports = {}
        for node in tree.body:
            if not isinstance(node, ast.ImportFrom) or node.module is None:
                continue
            if node.level == 1:
                source_module = node.module
            elif node.level == 0 and node.module.startswith("xbbg."):
                source_module = node.module.removeprefix("xbbg.")
            else:
                continue
            for alias in node.names:
                imports[alias.asname or alias.name] = (source_module, alias.name)
        return imports

    imports: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for name in registry["PACKAGE_EXPORTS"]:
        if name == "__version__":
            continue
        if name == "_core" or name in registry["MODULE_EXPORTS"]:
            imports[""].append((name, name))
            continue
        module, source_name = routes[name]
        # Follow facade imports to definitions so implicit re-exports cannot erase types.
        while source_name in reexports(module):
            module, source_name = reexports(module)[source_name]
        imports[module].append((source_name, name))

    lines = [
        "# Generated by scripts/generate_package_stub.py; do not edit.",
        "from __future__ import annotations",
        "",
    ]
    for module, names in sorted(imports.items()):
        names.sort(key=lambda item: (not item[0][0].isupper(), item[0].lower()))
        aliases = [f"{source} as {name}" for source, name in names]
        prefix = f"from .{module} import "
        single_line = prefix + ", ".join(aliases)
        if len(single_line) <= 120:
            lines.append(single_line)
        else:
            lines.append(prefix + "(")
            lines.extend(f"    {alias}," for alias in aliases)
            lines.append(")")
    lines.extend(["", "__version__: str", "", "__all__ = ["])
    lines.extend(f'    "{name}",' for name in registry["PACKAGE_EXPORTS"])
    lines.extend(
        [
            "]",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=PACKAGE_DIR / "__init__.pyi", help="Destination package stub")
    args = parser.parse_args()
    args.output.write_text(generate_stub(PACKAGE_DIR), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
