// @generated by defs/codegen/generate.py from defs/bloomberg.toml - DO NOT EDIT

/** Output format for reference and historical data. */
export const FORMATS = ['long', 'long_typed', 'long_metadata', 'semi_long'] as const;

/** Output format for reference and historical data. */
export type FormatKind = (typeof FORMATS)[number];

/** Extra spellings the engine also accepts, kept for compatibility. */
export const FORMAT_ALIASES = ['typed', 'metadata', 'with_metadata', 'wide'] as const;

/** Value used when the caller omits it. */
export const FORMAT_DEFAULT: FormatKind = 'long';

/** Canonical values as a list, for error text and tool descriptions. */
export const FORMAT_VALUES = 'long, long_typed, long_metadata, semi_long';

/** Per-value documentation, keyed by canonical spelling. */
export const FORMAT_DOCS: Readonly<Record<FormatKind, string>> = {
  long: 'Long format with all values as strings (default, backwards-compatible).',
  long_typed: 'Long format with typed value columns.',
  long_metadata: 'Long format with string values and dtype metadata column.',
  semi_long: 'Semi-long format with one row per ticker/timestamp and fields as columns.',
};

/** Canonical values keyed by their defs name. */
export const FORMAT_BY_NAME = {
  LONG: 'long',
  LONG_TYPED: 'long_typed',
  LONG_WITH_METADATA: 'long_metadata',
  SEMI_LONG: 'semi_long',
} as const;

/** Subscription behaviour when a consumer cannot keep up with Bloomberg. */
export const OVERFLOW_POLICIES = ['block', 'drop_newest'] as const;

/** Subscription behaviour when a consumer cannot keep up with Bloomberg. */
export type OverflowPolicy = (typeof OVERFLOW_POLICIES)[number];

/** Extra spellings the engine also accepts, kept for compatibility. */
export const OVERFLOW_POLICY_ALIASES = ['dropnewest'] as const;

/** Value used when the caller omits it. */
export const OVERFLOW_POLICY_DEFAULT: OverflowPolicy = 'drop_newest';

/** Canonical values as a list, for error text and tool descriptions. */
export const OVERFLOW_POLICY_VALUES = 'block, drop_newest';

/** Per-value documentation, keyed by canonical spelling. */
export const OVERFLOW_POLICY_DOCS: Readonly<Record<OverflowPolicy, string>> = {
  block:
    "Wait briefly on a bounded forwarding task, never on Bloomberg's callback thread; queue overflow or timeout closes with a data-loss error. Resubscribe for a fresh image.",
  drop_newest:
    "Close with a data-loss error when the consumer buffer is full; never waits on Bloomberg's callback thread. Resubscribe for a fresh image.",
};

/** Canonical values keyed by their defs name. */
export const OVERFLOW_POLICY_BY_NAME = {
  BLOCK: 'block',
  DROP_NEWEST: 'drop_newest',
} as const;

/** Field validation applied before a request is sent. */
export const VALIDATION_MODES = ['disabled', 'lenient', 'strict'] as const;

/** Field validation applied before a request is sent. */
export type ValidationMode = (typeof VALIDATION_MODES)[number];

/** Extra spellings the engine also accepts, kept for compatibility. */
export const VALIDATION_MODE_ALIASES = ['off', 'none'] as const;

/** Value used when the caller omits it. */
export const VALIDATION_MODE_DEFAULT: ValidationMode = 'disabled';

/** Canonical values as a list, for error text and tool descriptions. */
export const VALIDATION_MODE_VALUES = 'disabled, lenient, strict';

/** Per-value documentation, keyed by canonical spelling. */
export const VALIDATION_MODE_DOCS: Readonly<Record<ValidationMode, string>> = {
  disabled: 'No field validation (default).',
  lenient: 'Drop unknown fields and send the remaining ones.',
  strict: 'Reject the request when any field is unknown.',
};

/** Canonical values keyed by their defs name. */
export const VALIDATION_MODE_BY_NAME = {
  DISABLED: 'disabled',
  LENIENT: 'lenient',
  STRICT: 'strict',
} as const;

/** Verbosity of the Bloomberg C SDK's own logging. */
export const SDK_LOG_LEVELS = ['debug', 'error', 'fatal', 'info', 'off', 'trace', 'warn'] as const;

/** Verbosity of the Bloomberg C SDK's own logging. */
export type SdkLogLevel = (typeof SDK_LOG_LEVELS)[number];

/** Extra spellings the engine also accepts, kept for compatibility. */
export const SDK_LOG_LEVEL_ALIASES = ['warning'] as const;

/** Value used when the caller omits it. */
export const SDK_LOG_LEVEL_DEFAULT: SdkLogLevel = 'off';

/** Canonical values as a list, for error text and tool descriptions. */
export const SDK_LOG_LEVEL_VALUES = 'debug, error, fatal, info, off, trace, warn';

/** Per-value documentation, keyed by canonical spelling. */
export const SDK_LOG_LEVEL_DOCS: Readonly<Record<SdkLogLevel, string>> = {
  debug: 'Debug messages and above.',
  error: 'Errors and above.',
  fatal: 'Fatal errors only.',
  info: 'Informational messages and above.',
  off: 'Disable SDK logging (default).',
  trace: 'Most verbose SDK logging.',
  warn: 'Warnings and above.',
};

/** Canonical values keyed by their defs name. */
export const SDK_LOG_LEVEL_BY_NAME = {
  DEBUG: 'debug',
  ERROR: 'error',
  FATAL: 'fatal',
  INFO: 'info',
  OFF: 'off',
  TRACE: 'trace',
  WARN: 'warn',
} as const;

export const CDX_INFO_FIELDS = [
  'ROLLING_SERIES',
  'VERSION',
  'ON_THE_RUN_CURRENT_BD_INDICATOR',
  'CDS_FIRST_ACCRUAL_START_DATE',
  'NAME',
  'NUM_CURRENT_COMPANIES_CCY_TKR',
  'NUM_ORIG_COMPANIES_CRNCY_TKR',
  'PX_LAST',
] as const;

export const CDX_PRICING_FIELDS = [
  'PX_LAST',
  'PX_BID',
  'PX_ASK',
  'UPFRONT_LAST',
  'UPFRONT_BID',
  'UPFRONT_ASK',
  'CDS_FLAT_SPREAD',
  'UPFRONT_FEE',
  'PV_CDS_PREMIUM_LEG',
  'PV_CDS_DEFAULT_LEG',
] as const;

export const CDX_RISK_FIELDS = [
  'SW_CNV_BPV',
  'SW_EQV_BPV',
  'CDS_SPREAD_MID_MODIFIED_DURATION',
  'CDS_SPREAD_MID_CONVEXITY',
  'RECOVERY_RATE_SEN',
  'CDS_RECOVERY_RT',
] as const;

export const TA_STUDIES: Readonly<Record<string, string>> = Object.freeze({
  ado: 'adoStudyAttributes',
  adx: 'dmiStudyAttributes',
  al: 'alStudyAttributes',
  atr: 'atrStudyAttributes',
  bb: 'bollStudyAttributes',
  boll: 'bollStudyAttributes',
  bs: 'bsStudyAttributes',
  chko: 'chkoStudyAttributes',
  cmci: 'cmciStudyAttributes',
  dmi: 'dmiStudyAttributes',
  ema: 'emavgStudyAttributes',
  emavg: 'emavgStudyAttributes',
  etd: 'etdStudyAttributes',
  fear_greed: 'fgStudyAttributes',
  fg: 'fgStudyAttributes',
  goc: 'gocStudyAttributes',
  hurst: 'hurstStudyAttributes',
  ichimoku: 'gocStudyAttributes',
  ipmavg: 'ipmavgStudyAttributes',
  keltner: 'kltnStudyAttributes',
  kltn: 'kltnStudyAttributes',
  macd: 'macdStudyAttributes',
  mae: 'maeStudyAttributes',
  mao: 'maoStudyAttributes',
  maxmin: 'maxminStudyAttributes',
  mom: 'momentumStudyAttributes',
  momentum: 'momentumStudyAttributes',
  or: 'orStudyAttributes',
  parabolic: 'ptpsStudyAttributes',
  pcr: 'pcrStudyAttributes',
  pd: 'pdStudyAttributes',
  pivot: 'pivotStudyAttributes',
  ptps: 'ptpsStudyAttributes',
  rex: 'rexStudyAttributes',
  roc: 'rocStudyAttributes',
  rsi: 'rsiStudyAttributes',
  rv: 'rvStudyAttributes',
  sar: 'ptpsStudyAttributes',
  sma: 'smavgStudyAttributes',
  smavg: 'smavgStudyAttributes',
  stoch: 'tasStudyAttributes',
  tas: 'tasStudyAttributes',
  te: 'teStudyAttributes',
  tma: 'tmavgStudyAttributes',
  tmavg: 'tmavgStudyAttributes',
  trender: 'trenderStudyAttributes',
  tvat: 'tvatStudyAttributes',
  vat: 'vatStudyAttributes',
  vma: 'vmavgStudyAttributes',
  vmavg: 'vmavgStudyAttributes',
  williams: 'wlprStudyAttributes',
  wlpr: 'wlprStudyAttributes',
  wma: 'wmavgStudyAttributes',
  wmavg: 'wmavgStudyAttributes',
});

type StudyDefaults = Readonly<Record<string, string | number>>;

export const TA_DEFAULTS: Readonly<Record<string, StudyDefaults>> = Object.freeze({
  atrStudyAttributes: Object.freeze({
    maType: 'Simple',
    period: 14,
    priceSourceHigh: 'PX_HIGH',
    priceSourceLow: 'PX_LOW',
    priceSourceClose: 'PX_LAST',
  }),
  bollStudyAttributes: Object.freeze({
    period: 20,
    upperBand: 2.0,
    lowerBand: 2.0,
    priceSourceClose: 'PX_LAST',
  }),
  dmiStudyAttributes: Object.freeze({
    period: 14,
    priceSourceHigh: 'PX_HIGH',
    priceSourceLow: 'PX_LOW',
    priceSourceClose: 'PX_LAST',
  }),
  emavgStudyAttributes: Object.freeze({ period: 20, priceSourceClose: 'PX_LAST' }),
  macdStudyAttributes: Object.freeze({
    maPeriod1: 12,
    maPeriod2: 26,
    sigPeriod: 9,
    priceSourceClose: 'PX_LAST',
  }),
  rsiStudyAttributes: Object.freeze({ period: 14, priceSourceClose: 'PX_LAST' }),
  smavgStudyAttributes: Object.freeze({ period: 20, priceSourceClose: 'PX_LAST' }),
  tasStudyAttributes: Object.freeze({
    periodK: 14,
    periodD: 3,
    periodDS: 3,
    periodDSS: 3,
    priceSourceHigh: 'PX_HIGH',
    priceSourceLow: 'PX_LOW',
    priceSourceClose: 'PX_LAST',
  }),
  tmavgStudyAttributes: Object.freeze({ period: 20, priceSourceClose: 'PX_LAST' }),
  vmavgStudyAttributes: Object.freeze({ period: 20, priceSourceClose: 'PX_LAST' }),
  wmavgStudyAttributes: Object.freeze({ period: 20, priceSourceClose: 'PX_LAST' }),
});

export type VolSurfacePreset =
  | 'DELTA_1M_2M'
  | 'MONEYNESS_30D'
  | 'MONEYNESS_60D'
  | 'MONEYNESS_3M'
  | 'MONEYNESS_6M'
  | 'MONEYNESS_12M';

export type IndexMemberField = 'INDX_MWEIGHT' | 'INDX_MEMBERS' | 'INDX_MEMBERS3';
